
import { NewInventoryItemData } from '@/hooks/useInventory';

export const inventoryDataToImport: NewInventoryItemData[] = [
  { name: 'Hettegenser', brand: 'Finstad skole', color: 'Mørkeblå', location: 'Venstre hylle', shelf: '1', description: 'JERZEES / 50% bomull / 50% polyester', size: 'L', owner: 'EB', notes: '' },
  { name: 'Ullgenser', brand: 'Trico', color: 'Blå', location: 'Venstre hylle', shelf: '1', description: 'Ullgenser', size: 'Ca L størrelse', owner: '', notes: '' },
  { name: 'superundertøy trøye', brand: '', color: 'Blå', location: 'Venstre hylle', shelf: '2', description: '100% polyester', size: 'XL', owner: '', notes: '' },
  { name: 'superundertøy trøye', brand: 'Frank Shorter', color: 'Svart', location: 'Venstre hylle', shelf: '2', description: 'Tynn trøye / 100% Polyester', size: 'L', owner: '', notes: 'Eivind?' },
  { name: 'superundertøy trøye', brand: 'Helly Hansen', color: 'Svart', location: 'Venstre hylle', shelf: '2', description: 'Svart med hvite striper', size: 'M', owner: 'SB', notes: '' },
  { name: 'superundertøy trøye', brand: 'Stormberg', color: 'Svart', location: 'Venstre hylle', shelf: '2', description: 'Svart med hvite linjer', size: 'M', owner: 'SB', notes: '' },
  { name: 'superundertøy trøye', brand: 'Devold', color: 'Turkis', location: 'Venstre hylle', shelf: '2', description: 'Blå/grønnaktig', size: 'M', owner: 'SB', notes: 'SB fikk i jul av MI 2022?' },
  { name: 'Caps', brand: 'Barklay', color: 'Svart/Hvit', location: 'Venstre hylle', shelf: '3', description: '', size: 'onesize', owner: '', notes: '' },
  { name: 'Hals', brand: 'IA', color: 'Blå', location: 'Venstre hylle', shelf: '3', description: '100% Polyester(Blå fleecebuff)', size: 'onesize', owner: 'EB', notes: 'EB gammelt?' },
  { name: 'Hals', brand: 'Devold', color: 'Svart', location: 'Venstre hylle', shelf: '3', description: 'Buff', size: 'onesize', owner: '', notes: 'SB gave fra jobb?' },
  { name: 'Håndleddbeskyttere', brand: '', color: 'Svart', location: 'Venstre hylle', shelf: '3', description: '', size: '', owner: '', notes: '' },
  { name: 'Lue', brand: '', color: 'Gul', location: 'Venstre hylle', shelf: '3', description: '', size: 'onesize', owner: '', notes: '' },
  { name: 'Lue', brand: 'Moods of Norway', color: 'Hvit/Blå/Rød', location: 'Venstre hylle', shelf: '3', description: '', size: 'onesize', owner: 'SB', notes: '' },
  { name: 'Lue', brand: 'Devold', color: 'Svart', location: 'Venstre hylle', shelf: '3', description: 'Tynn lue', size: '58', owner: '', notes: 'SB gave fra jobb?' },
  { name: 'Lue', brand: 'NY Yankees', color: 'Grå', location: 'Venstre hylle', shelf: '3', description: '', size: '', owner: 'SB', notes: '' },
  { name: 'Lue', brand: 'Steffnes', color: 'Beige', location: 'Venstre hylle', shelf: '3', description: 'Wollsiegel', size: '', owner: 'EB', notes: '' },
  { name: 'Lue', brand: 'Smiley?', color: 'Hvit', location: 'Venstre hylle', shelf: '3', description: 'Hvit lue med smilefjes', size: 'onesize', owner: '', notes: '' },
  { name: 'Sikring snowboard', brand: '', color: '', location: 'Venstre hylle', shelf: '3', description: '', size: '', owner: '', notes: '' },
  { name: 'Skjerf', brand: 'Moods of Norway', color: 'Hvit/Blå/Rød', location: 'Venstre hylle', shelf: '3', description: '', size: 'onesize', owner: 'SB', notes: '' },
  { name: 'Sokk', brand: 'Ullrokken', color: 'Svart/grå', location: 'Venstre hylle', shelf: '3', description: 'Tjukk sokk', size: '43-46', owner: 'EB', notes: '' },
  { name: 'Sokk', brand: 'Ulvang', color: 'Svart', location: 'Venstre hylle', shelf: '3', description: 'Tynnere ullsokk', size: '40-43', owner: '', notes: '' },
  { name: 'Sokk', brand: 'Ullrokken', color: 'Svart/grå', location: 'Venstre hylle', shelf: '3', description: 'Tjukk sokk', size: '39-42', owner: '', notes: '' },
  { name: 'Sokk', brand: 'Ulvang', color: 'Grå', location: 'Venstre hylle', shelf: '3', description: 'Tynnere ullsokk. KUN 1 SOKK!', size: '40-45', owner: '', notes: 'NB! Kun 1 sokk!!!!' },
  { name: 'SOKKER', brand: '', color: '', location: 'Venstre hylle', shelf: '3', description: 'Masse sokker', size: '', owner: '', notes: 'Mangler andre halvdel av venstre hylle nr. 4. masse sokker.' },
  { name: 'Hansker', brand: 'Norheim', color: 'Svart/grå', location: 'Venstre hylle', shelf: '4', description: '50% polyester, 20% Pu 30% Nylon', size: '10', owner: 'EB', notes: 'Litt store for SB' },
  { name: 'Hansker', brand: 'Thinsulate', color: 'Blå/Svart', location: 'Venstre hylle', shelf: '4', description: 'SkiBum Sportswear', size: '8 og 1/2?', owner: 'EB', notes: 'Litt store for SB' },
  { name: 'Skibukse', brand: 'Nørrøna', color: 'Svart', location: 'Venstre hylle', shelf: '4', description: 'Norrønamerke på høyre bukse. 100% Mikrofiber/polyester', size: 'L', owner: 'EB', notes: 'EB gammelt?' },
  { name: 'Skibukse', brand: 'Five Seasons', color: 'Svart', location: 'Venstre hylle', shelf: '4', description: 'Mountex', size: 'L', owner: 'EB', notes: 'EB gammelt?' },
  { name: 'Skibukse', brand: 'Tenson', color: 'Svart', location: 'Venstre hylle', shelf: '4', description: 'MPC - 100% polyester', size: 'XXL', owner: 'EB', notes: 'EB gammelt?' },
  { name: 'Skihansker', brand: 'Bjørn Dæhlie', color: 'svart/grå/hvit', location: 'Venstre hylle', shelf: '4', description: '', size: 'L/9', owner: '', notes: '' },
  { name: 'Votter', brand: 'Hestra', color: 'Svart/Beige', location: 'Venstre hylle', shelf: '4', description: '100% Polyester. Vintervotter alpint?', size: '7', owner: 'EB', notes: 'Eivind sine alpinvotter?' },
  { name: 'Snowboardbukse', brand: 'Head', color: 'Brun/lyseblå', location: 'Venstre hylle', shelf: '5', description: 'Simen sin snowboardbukse', size: '40', owner: 'SB', notes: '' },
  { name: 'Utebukse', brand: 'NRK', color: 'mørkeblå', location: 'Venstre hylle', shelf: '5', description: 'NRK bukse 100% polyester', size: 'S', owner: '', notes: 'Gamle til V' },
  { name: 'Utebukse', brand: 'North Peak', color: 'lysegrå', location: 'Venstre hylle', shelf: '5', description: '', size: 'XS', owner: 'SB', notes: 'Simen sin gamle bukse' },
  { name: 'Fleecegenser', brand: 'Marmot', color: 'Svart', location: 'Venstre hylle', shelf: '6', description: '100% polyester / Polartec', size: 'M/S?', owner: 'KB', notes: 'KB sin?? Litt kort og vi' },
  { name: 'Fleecegenser', brand: 'FTM Sports', color: 'Svart', location: 'Venstre hylle', shelf: '6', description: '', size: 'Ca L størrelse. Knut sin?', owner: 'KB', notes: '' },
  { name: 'Turbukse', brand: 'Gaupa', color: 'Grå/svart', location: 'Venstre hylle', shelf: '6', description: '65% Polyester, 35% Bomull', size: '16', owner: 'SB', notes: 'SB gammelt?' },
  { name: 'Turbukse', brand: 'Vikafjell', color: 'Svart', location: 'Venstre hylle', shelf: '6', description: '65% Polyester, 35% Bomull. Relativt tynn, sommerturbukse', size: 'S', owner: 'MI', notes: 'MI kjøpt inn sommeren 2022/2023' },
  { name: 'Lue', brand: 'Mario Conti', color: 'Mørkegrå', location: 'Venstre hylle', shelf: '', description: '100 %', size: 'onesize', owner: 'SB', notes: 'Ikke lagt noen sted enda. Tar kanskje med ned til Oslo' },
  { name: 'Slippers', brand: 'Spume', color: 'Svart/blå/Hvit', location: 'Venstre hylle', shelf: '', description: 'Litt ødelagt, men kan brukes til badet', size: '41', owner: 'EB', notes: 'EB gammelt?' },
];
