// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oztvpaviseudhobxmzgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dHZwYXZpc2V1ZGhvYnhtemdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Njg0MTQsImV4cCI6MjA2MDI0NDQxNH0.t7fko5PqHOr5cXI0pnDEvKP4RYfEVgKr9Hn5ufiXS80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);